# Course structure {.unnumbered}

This course is broken into 'sessions' A Session is roughly 4 hours of combined lecture and labs, corresponding to 1 day workshop or 1 week of normal class.

In the Type column, you see different Types of material.

-   Lectures are just that, I talk and hopefully you don't fall asleep.
-   Application exercises are done in class, by everyone, and I'll help you if you get stuck, but you don't turn them in to be graded.
-   Labs are also exercises that are done in class, by everyone, but you will turn them in (I'll show you how) and I'll check them out to make sure you did it right.
-   Homework is that thing you do outside of class, by everyone, and you turn it in to be graded.

I encourage together-work, but don't just copy your friend, it does neither you nor them any good.
Plagiarism is frowned upon; don't do it.

## Schedule {.unnumbered}

| Session | Part   | Title                                             | Type                     |
|---------|--------|---------------------------------------------------|--------------------------|
| 1       | 1      | Welcome to data science!                          | Lecture                  |
| 1       | 2      | UN Votes                                          | Application exercise     |
| 1       | 3      | Meet the toolkit: Programming                     | Lecture                  |
| 1       | 4      | The Bechdel test                                  | Application exercise     |
| 1       | 5      | Meet the toolkit: Version control & collaboration | Lecture                  |
| 1       | 6      | Hello R                                           | Lab                      |
| 1       | 7      | Pet names                                         | Homework                 |
| **2**   | **1**  | **Data and visualisation**                        | **Lecture**              |
| **2**   | **2**  | **Visualising data with ggplot2**                 | **Lecture**              |
| **2**   | **3**  | **Visualising numerical data**                    | **Lecture**              |
| **2**   | **4**  | **Visualising categorical data**                  | **Lecture**              |
| **2**   | **5**  | **StarWars + Dataviz**                            | **Application exercise** |
| **2**   | **6**  | **Plastic waste**                                 | **Lab**                  |
| **2**   | **7**  | **Airbnb listings in Edinburgh**                  | **Homework**             |
| 3       | 1      | Tidy data                                         | Lecture                  |
| 3       | 2      | Grammar of data wrangling                         | Lecture                  |
| 3       | 3      | Working with a single data frame                  | Lecture                  |
| 3       | 4      | Working with multiple data frames                 | Lecture                  |
| 3       | 5      | Tidying data                                      | Lecture                  |
| 3       | 6      | Hotels + Data wrangling                           | Application exercise     |
| 3       | 7      | Nobel laureates                                   | Lab                      |
| 3       | 8      | Road traffic accidents                            | Homework                 |
| **4**   | **1**  | **Data types**                                    | **Lecture**              |
| **4**   | **2**  | **Data classes**                                  | **Lecture**              |
| **4**   | **3**  | **Importing data**                                | **Lecture**              |
| **4**   | **4**  | **Recoding data**                                 | **Lecture**              |
| **4**   | **5**  | **Hotels + Data types**                           | **Application exercise** |
| **4**   | **6**  | **Nobels + Sales + Data import**                  | **Application exercise** |
| **4**   | **7**  | **La Quinta is Spanish for next to Denny's**      | **Lab**                  |
| **4**   | **8**  | **College majors**                                | **Homework**             |
| 2       | 5      | Tips for effective data visualization             | Lecture                  |
| 2       | 5      | Brexit + Telling stories with dataviz             | Application exercise     |
| 2       | 5      | Take a sad plot and make it better                | Lab                      |
| 2       | 5      | La Quinta is Spanish for next to Denny's, Pt. 2   | Homework                 |
| **2**   | **6**  | **Scientific studies and confounding**            | **Lecture**              |
| **2**   | **6**  | **Simpson's paradox**                             | **Lecture**              |
| **2**   | **6**  | **Doing data science**                            | **Lecture**              |
| **2**   | **6**  | **Simpson's paradox**                             | **Lab**                  |
| **2**   | **6**  | **Legos**                                         | **Homework**             |
| 2       | 7      | Web scraping                                      | Lecture                  |
| 2       | 7      | Scraping top 250 movies on IMDB                   | Lecture                  |
| 2       | 7      | Web scraping considerations                       | Lecture                  |
| 2       | 7      | IMDB + Web scraping                               | Application exercise     |
| 2       | 7      | Work on projects                                  | Lab                      |
| 2       | 7      | Work on projects                                  | Homework                 |
| **2**   | **8**  | **Functions**                                     | **Lecture**              |
| **2**   | **8**  | **Iteration**                                     | **Lecture**              |
| **2**   | **8**  | **University of Edinburgh Art Collection**        | **Lab**                  |
| **2**   | **8**  | **Money in politics**                             | **Homework**             |
| 3       | 9      | Misrepresentation                                 | Lecture                  |
| 3       | 9      | Data privacy                                      | Lecture                  |
| 3       | 9      | Algorithmic bias                                  | Lecture                  |
| 3       | 9      | Conveying the right message through visualisation | Lab                      |
| 3       | 9      | Project proposals                                 | Project                  |
| 3       | 9      | Peer review of project proposals                  | Homework                 |
| **4**   | **10** | **Fitting and interpreting models**               | **Lecture**              |
| **4**   | **10** | **Modelling nonlinear relationships**             | **Lecture**              |
| **4**   | **10** | **Models with multiple predictors**               | **Lecture**              |
| **4**   | **10** | **More models with multiple predictors**          | **Lecture**              |
| **4**   | **10** | **Grading the professor, Pt 1**                   | **Lab**                  |
| **4**   | **10** | **Bike rentals in DC**                            | **Homework**             |
| 4       | 11     | Logistic regression                               | Lecture                  |
| 4       | 11     | Prediction and overfitting                        | Lecture                  |
| 4       | 11     | Feature engineering                               | Lecture                  |
| 4       | 11     | Grading the professor, Pt. 1                      | Lab                      |
| 4       | 11     | Exploring the GSS                                 | Homework                 |
| **4**   | **12** | **Cross validation**                              | **Lecture**              |
| **4**   | **12** | **The Office, Part 1**                            | **Application exercise** |
| **4**   | **12** | **The Office, Part 2**                            | **Application exercise** |
| **4**   | **12** | **Bootstrapping**                                 | **Lecture**              |
| **4**   | **12** | **Work on projects**                              | **Lab**                  |
| **4**   | **12** | **Grading the professor, Pt. 2**                  | **Homework**             |
| 4       | 13     | Quantifying uncertainty                           | Lecture                  |
| 4       | 13     | Bootstrapping                                     | Lecture                  |
| 4       | 13     | Hypothesis testing                                | Lecture                  |
| 4       | 13     | Inference overview                                | Lecture                  |
| 4       | 13     | Smoking during pregnancy                          | Lab                      |
| 4       | 13     | Modelling the GSS                                 | Homework                 |
| **5**   | **14** | **Text analysis**                                 | **Lecture**              |
| **5**   | **14** | **Comparing texts**                               | **Lecture**              |
| **5**   | **14** | **Interactive web apps**                          | **Lecture**              |
| **5**   | **14** | **Machine learning**                              | **Lecture**              |
| **5**   | **14** | **Collaborating on GitHub**                       | **Lab**                  |
| **5**   | **14** | **Wrap up**                                       | **Homework**             |
| 5       | 15     | Bayesian inference                                | Lecture                  |
| 5       | 15     | Building interactive web apps, Pt. 1              | Lecture                  |
| 5       | 15     | Building interactive web apps, Pt. 1              | Lecture                  |
| 5       | 15     | Project presentations                             | Lab                      |
| 5       | 15     | N/A                                               | Homework                 |
