# Getting started {.unnumbered}

We will go over this in Lab 1, but if you want to start now, please go ahead.
You'll need access to GitHub and a version of RStudio (either Cloud, or on your computer)

## GitHub {.unnumbered}

You'll need a GitHub account.
Go to [GitHub](https://github.com/) and sign up.
Once you have a GitHub account, I can invite you to labs and homework.

## RStudio {.unnumbered}

If you are new to all this, I'd recommend starting with RStudio Cloud.
You can always change later.

### RStudio Cloud {.unnumbered}

Just go to [RStudio Cloud](https://rstudio.cloud/) and click "Get Started For Free".
Follow the steps for Cloud Free.
That's it.
We will talk about how you will use this on day 1 of class.

### RStudio on your computer {.unnumbered}

While this is a little more complicated, it will be well worth the effort if you plan on continuing to use RStudio.
Do the following to get started:

-   Download and install R. The official instructions are on [CRAN](https://cran.r-project.org/)
-   Download and install [RStudio Desktop Free](https://www.rstudio.com/products/rstudio/download/)
-   You will need a local copy of git. Use the instructions here: [Using Git with RStudio](https://r-bio.github.io/git-installation/). This might be tricky, and we can work it out together if you run into trouble.
